apiVersion: v1
kind: Namespace
metadata:
  name: pso-analytics
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pso-collect
  namespace: pso-analytics
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pso-collect
rules:
- apiGroups: ["", "apps", "storage.k8s.io"]
  resources: ["persistentvolumes", "persistentvolumeclaims", "statefulsets", "deployments", "pods", "storageclasses"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pso-collect
  namespace: pso-analytics
subjects:
- kind: ServiceAccount
  name: pso-collect
  namespace: pso-analytics
roleRef:
  kind: ClusterRole
  name: pso-collect
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pso-collect-secret
  namespace: pso-analytics
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pso-collect-secret
  namespace: pso-analytics
subjects:
- kind: ServiceAccount
  name: pso-collect
  namespace: pso-analytics
roleRef:
  kind: ClusterRole
  name: pso-collect-secret
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Service
metadata:
  name: pso-analytics-gui
  namespace: pso-analytics
  labels:
    app: pso-analytics-gui
spec:
  ports:
  - port: 80
    name: web
  selector:
    app: pso-analytics-gui
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pso-analytics-gui
  namespace: pso-analytics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pso-analytics-gui
  template:
    metadata:
      labels:
        app: pso-analytics-gui
    spec:
      serviceAccountName: pso-collect
      containers:
      - name: pso-analytics-gui
        image: quay.io/purestorage/pso-analytics-gui:latest
        ports:
        - containerPort: 80
        imagePullPolicy: Always
      - name: redis
        image: redis:alpine
      restartPolicy: Always
