apiVersion: v1
description: A Helm chart for Pure Service Orchestrator Explorer
name: pso-explorer
appVersion: "devel"
version: latest-devel
icon: https://raw.githubusercontent.com/PureStorage-OpenConnect/pso-explorer/master/pso-explorer.png
keywords:
- purestorage
maintainers:
- name: Remko Deenik
  email: pso-explorer@purestorage.com