{{ if .Values.ingress.enabled }}
{{ if .Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
apiVersion: networking.k8s.io/v1
{{ else }}
apiVersion: networking.k8s.io/v1beta1
{{ end }}
kind: Ingress
metadata:
  name: {{ include "pso-explorer.fullname" . }}
  labels:
    app: {{ include "pso-explorer.fullname" . }}
    helm.sh/chart: {{ include "pso-explorer.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
{{ toYaml .Values.ingress.annotations | indent 4 }}
spec:
{{ if .Values.ingress.tls }}
  tls:
    - hosts:
      - {{ .Values.ingress.hostname | quote }}
      secretName: {{ .Values.ingress.secretName | default (printf "%s-tls" (include "pso-explorer.fullname" .)) }}
{{ end }}
  rules:
  - host: {{ .Values.ingress.hostname }}
    http:
      paths:
      - path: {{ .Values.ingress.path }}
        backend:
{{ if .Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
          service:
            name: {{ include "pso-explorer.fullname" . }}
            port: 
              number: 80
{{ else }}
          serviceName: {{ include "pso-explorer.fullname" . }}
          servicePort: 80
{{ end }}
{{ end }}