apiVersion: v1
kind: Secret
metadata:
  name: {{ template "pso-explorer.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "pso-explorer.name" . }}
    chart: {{ template "pso-explorer.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
  username: {{ required "credentials.username field is required!" .Values.credentials.username | b64enc | quote}}
  password: {{ required "credentials.passwordHash field is required!" .Values.credentials.passwordHash | b64enc | quote}}
