# Default values for pso-explorer.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# specify the timeouts in seconds used by PSO Explorer
timeouts:
  # determines how often the dashboard view refreshes (page reloads)
  dashboard_refresh: "60"
  # determines how long cached data is valid. As long as the cache is valid, no new
  # data will be fetched from K8S or the Pure Storage systems.
  cache_refresh: "300"

credentials:
  # Authentication for PSO eXplorer is used to secure views that potentially show sensitive data
  # like API tokens. However if you want to secure all views, you can set anonymousAccess to
  # false. Once set to false, the user must authenticate before being able to access any view.
  anonymousAccess: true
  # Username used for authentication
  username: pureuser
  # Hashed password, use the following to create the hash 
  # htpasswd -bnBC 10 "" 'password' | tr -d ':\n'
  passwordHash: "$2y$10$R1OPJ7MX9qHfps69y/NCv.II/UJGWvHZU/nnNDi6QSFxY90DbZuvS"

images:
  webserver:
    repository: quay.io/purestorage/pso-explorer
    tag: v0.5.6-devel
    pullPolicy: Always
  redis:
    repository: redis
    tag: alpine
    pullPolicy: IfNotPresent

# service.type can be LoadBalancer or ClusterIP
service:
  type: LoadBalancer
  port: 80

## Configure the ingress object to hook into existing infastructure
## ref : http://kubernetes.io/docs/user-guide/ingress/
## OPTIONALLY you can set .Values.ingress.secretName to set which secret to use
##
ingress:
  enabled: false
  tls: false
  hostname: psox.foo.bar
  annotations: {}
    # kubernetes.io/ingress.class: "nginx"
    # secretName: my-tls-cert
    # kubernetes.io/tls-acme: "true"
  path: /

# specify the service account name for this app
clusterrolebinding:
  serviceAccount:
    name: pso-explorer

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
